# Use the lightweight Alpine Linux as a base image
FROM alpine:latest

# Set the working directory
WORKDIR /data

# Expose the desired port
EXPOSE 8000
EXPOSE 5432

# Copy the application code into the container
COPY . .

# Update the package repository and install necessary packages
RUN apk update && \
    apk add --no-cache build-base python3 py3-pip python3-dev postgresql-dev openblas-dev lapack-dev libffi-dev openssl-dev

# Create and activate a virtual environment
RUN python3 -m venv .venv
RUN source .venv/bin/activate

# Upgrade pip within the virtual environment with --no-cache-dir
RUN .venv/bin/python3 -m pip install --no-cache-dir --upgrade pip

# Install project dependencies (use pip3 to install packages)
RUN .venv/bin/python3 -m pip install --no-cache-dir -r requirements.txt
RUN chmod +x *.py

# Run the Uvicorn server directly
#CMD ["uvicorn", "app_api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
CMD [ ".venv/bin/python3", "main.py" ]

# Run the application and API
# RUN python3 -m uvicorn app_api:app --reload
#CMD ["python3", "main.py", "/data/DataSource", "/data/DataTarget"]
